# -*- coding: utf-8 -*-
"""Ex_3_NLP_Sentiment_Analysis_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10yizp0zrX2O5zod91SL1xBDpObtFNBvc
"""

"""NLP project, Sentiment Analysis
Authors: Luiz Otavio de Quadros, Mengqi Liu, Nur Rodríguez Boada."""

# Install required packages (only needed once)
!pip install pyarrow fsspec

# Import libraries
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

#STEP 1
print("1. Loading the SST-2 dataset (train, validation)...")

splits = {
    'train': 'data/train-00000-of-00001.parquet',
    'validation': 'data/validation-00000-of-00001.parquet'
}

# Load datasets
df_train = pd.read_parquet("hf://datasets/stanfordnlp/sst2/" + splits["train"])
df_val = pd.read_parquet("hf://datasets/stanfordnlp/sst2/" + splits["validation"])


# Extract data
train_texts = df_train['sentence'].tolist()
train_labels = df_train['label'].tolist()

val_texts = df_val['sentence'].tolist()
val_labels = df_val['label'].tolist()

print(f"Train size: {len(train_texts)}")
print(f"Validation size: {len(val_texts)}")

#STEP 2
print("\n2. Converting text into numerical features using TF-IDF...")

# Create TF-IDF vectorizer
# - stop_words='english' removes common words (like "the", "is")
# - ngram_range=(1,2) captures single words AND short phrases
vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1, 2))

# IMPORTANT: Fit ONLY on training data (prevents data leakage)
X_train = vectorizer.fit_transform(train_texts)

# Transform validation data using SAME vocabulary
X_val = vectorizer.transform(val_texts)

print("Feature matrix shape:", X_train.shape)
print("Feature matrix shape:", X_val.shape)

#STEP 3
print("\n3. Training Logistic Regression model...")

# Initialize model
model = LogisticRegression(max_iter=1000, random_state=42)

# Train model on training data
model.fit(X_train, train_labels)

print("Model training complete.")

#STEP 4
print("\n4. Evaluating model...")

# Predict labels for validation set
val_predictions = model.predict(X_val)

# Calculate accuracy
accuracy = accuracy_score(val_labels, val_predictions)

print(f"\nAccuracy: {accuracy * 100:.2f}%\n")

# Detailed performance report
print("Classification Report:")
print(classification_report(val_labels, val_predictions))

#STEP 5
print("\n5. Testing custom sentences...")

#Created sentences that are here only to check the human perception of the code. They do not impact on the training and can be written randomly.
custom_reviews = [
    "Oh, brilliant. Another superhero movie with exactly the same plot.",  # Sarcastic negative.
    "The worst film I have seen in my beautiful life", # Negative but tricky
    "The worst film I have seen in my life", # Negative
    "A terrifyingly good thriller!",  # Positive but tricky
    "It was a fantastic movie, I highly recommend it!"  # Clearly positive
]

# Convert to TF-IDF features
custom_vectors = vectorizer.transform(custom_reviews)

# Predict sentiment
custom_preds = model.predict(custom_vectors)

# Print results
for review, pred in zip(custom_reviews, custom_preds):
    sentiment = "Positive" if pred == 1 else "Negative"
    print(f"\nReview: {review}")
    print(f"Predicted Sentiment: {sentiment}")

#STEP 6
print("\n6. Finding uncertain predictions...")

# Get probability scores instead of just labels
probabilities = model.predict_proba(X_val)

doubtful_reviews = []

# Loop through validation data
for i in range(len(val_texts)):
    prob_positive = probabilities[i][1]  # probability of class "Positive"

    # If model confidence is near 50%, it's uncertain between 45% and 55%.
    if 0.45 <= prob_positive <= 0.55:
        doubtful_reviews.append({
            'text': val_texts[i],
            'true_label': val_labels[i],
            'confidence': prob_positive
        })

print(f"Found {len(doubtful_reviews)} uncertain predictions.\n")

# Show 30 examples to be manually analysed and later manualy weighted.
for case in doubtful_reviews[:30]:
    sentiment = "Positive" if case['true_label'] == 1 else "Negative"
    print(f"Confidence: {case['confidence']*100:.1f}%")
    print(f"True Label: {sentiment}")
    print(f"Text: {case['text']}\n")

#STEP 7
print("\n7. Performing manual weight adjustments...")

# Get vocabulary (word → index mapping)
vocab = vectorizer.vocabulary_

# Check in the previous uncertainty predictions step the key words that the model is having difficulties.
# Custom word weights (forcing model behavior)
custom_flags = {
    'yawns': -50.0,
    'howlers': -50.0,
    'repulsively': -50.0,
    'mundane': -50.0,
    'pity': -30.0,
    "skip": -20.0,
    "fascinates": 30.0,
    "play well": 30.0,
    "easy way out": -30.0,
    "smartest": 50.0,
    "sincere":20.0,
    "celebration":10.0,
    "chokes":-50.0,
    "lots of":50.0,
    "lack of": -30.0,
    "endurance": -50.0,
    "no interest": -30.0,
    "unwise": -30.0,
    "fool": -20.0,
    "heartwarming": 30.0
}

# Modify model weights directly
for word, new_weight in custom_flags.items():
    if word in vocab:
        word_id = vocab[word]
        model.coef_[0][word_id] = new_weight
        print(f"Adjusted '{word}' → {new_weight}")
    else:
        print(f"'{word}' not found in vocabulary")

#STEP 8
print("\n8. Re-evaluating model after weight adjustments...")

# Predict labels for validation set with adjusted weights
val_predictions_adjusted = model.predict(X_val)

# Calculate accuracy
accuracy_adjusted = accuracy_score(val_labels, val_predictions_adjusted)

print(f"\nAdjusted Accuracy: {accuracy_adjusted * 100:.2f}%\n")

# Detailed performance report
print("Adjusted Classification Report:")
print(classification_report(val_labels, val_predictions_adjusted))